---

# cert-manager install process adapted from:
# https://docs.cert-manager.io/en/latest/getting-started/install/kubernetes.html#installing-with-regular-manifests
- name: Create namespace for cert-manager
  k8s:
    context: "{{ KUBE_CONTEXT }}"
    kubeconfig: "{{ KUBE_CONFIG }}"
    wait: yes
    validate:
      fail_on_error: yes
      strict: yes
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cert-manager
  register: cert_manager

- name: Temporarily disable validation for cert-manager namespace
  k8s:
    context: "{{ KUBE_CONTEXT }}"
    kubeconfig: "{{ KUBE_CONFIG }}"
    wait: yes
    validate:
      fail_on_error: yes
      strict: yes
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cert-manager
        labels:
          certmanager.k8s.io/disable-validation: "true"
  when: cert_manager is changed

- name: Deploy cert-manager and Let's Encrypt
  k8s:
    context: "{{ KUBE_CONTEXT }}"
    kubeconfig: "{{ KUBE_CONFIG }}"
    wait: yes
    # FIXME: cert-manager.yaml doesn't validate, so this is disabled for now.
    # Maybe the next version will validate?
    # validate:
    #   fail_on_error: yes
    #   strict: yes
    definition: "{{ lookup('template', item) }}"
  with_items:
    - letsencrypt/cert-manager.yaml
    - letsencrypt/issuers.yaml

# ingress-nginx installation process adapted from:
# https://kubernetes.github.io/ingress-nginx/deploy/#prerequisite-generic-deployment-command
- name: Deploy Nginx Ingress Controller
  k8s:
    context: "{{ KUBE_CONTEXT }}"
    kubeconfig: "{{ KUBE_CONFIG }}"
    wait: yes
    validate:
      fail_on_error: yes
      strict: yes
    definition: "{{ lookup('template', item) }}"
  with_items:
    - ingress-nginx/mandatory.yaml
    - ingress-nginx/cloud-generic.yaml
    - ingress-nginx/patch-configmap.yaml
  when: kube_cluster_install_ingress
