---

# ----------------------------------------------------------------------------
# ansible-aws-web-stacks: Provision a stack with AWS CloudFormation.
# ----------------------------------------------------------------------------

default_cloudformation_stack:

  profile: "{{ aws_profile | mandatory }}"
  region: "{{ aws_region | mandatory }}"
  stack_name: "{{ stack_name | mandatory }}"
  template_bucket: "aws-web-stacks-{{ project_name }}"
  template_local_path: '{{ playbook_dir + "/../files/microk8s-no-nat.yaml" }}'

  template_parameters:
    AssetsBucketAccessControl: "Private"
    AssetsCloudFrontCertArn: ""
    AssetsUseCloudFront: "false"
    UseAES256Encryption: "true"
    SshCidr: "0.0.0.0/0"
    ContainerInstanceType: m4.large
    DatabaseClass: db.t2.small
    DatabaseEngineVersion: "11"
    DatabaseUser: "{{ project_name }}_{{ env_name }}"
    DatabaseName: "{{ project_name }}_{{ env_name }}"
    DatabaseParameterGroupFamily: postgres11
    DomainName: ""
    DomainNameAlternates: ""
    ElasticsearchInstanceType: t2.small.elasticsearch
    ElasticsearchVersion: "7.1"
    ElasticsearchVolumeSize: "10"
    PrimaryAZ: "{{ aws_region }}a"
    SecondaryAZ: "{{ aws_region }}b"
    SecretKey: "NOTUSED"
  tags:
    Environment: "{{ env_name }}"

cloudformation_stack_overrides:
  template_parameters:
    DatabasePassword: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33623033663563656365663930633263356438613232656330386364616638356565326435333538
          6438386134343730656331323363393638623166376466620a303438646161333564643462646261
          64646663646664303662323139633832306530323262323131353863363463313165363565653334
          6236643231303962620a396239303966373138373738326263383039613066336466663333383737
          62313166303637643531633030343537326133346563663731323333363235386636393936613263
          3232356665343839336338633732656164666139393432663463
    KeyName: copelco

# Combine default stack parameters with customizations
cloudformation_stack: >-
  {{ default_cloudformation_stack |
  combine(cloudformation_stack_overrides, recursive=True)
  }}
