---

# ----------------------------------------------------------------------------
# ansible-aws-web-stacks: Provision a stack with AWS CloudFormation.
# ----------------------------------------------------------------------------

cloudformation_stack_overrides:
  template_parameters:
    DatabasePassword: "CHANGE-ME-CHANGE-ME"
    KeyName: copelco
