---

- hosts: aws_ec2
  become: true
  tasks:
    - name: Install microk8s
      snap:
        name: microk8s
        classic: yes
        channel: 1.16/stable
    - name: Check status
      command: microk8s.status --wait-ready --timeout 60 --yaml
      register: microk8s_status
    - name: Parse status yaml
      set_fact:
        _status: "{{ microk8s_status.stdout | from_yaml }}"
    - name: Enable addons
      command: "microk8s.enable {{ item }}"
      when: _status['addons'][item] == "disabled"
      loop: "{{ microk8s_addons }}"
